PrimeFaces.locales['el'] = {
    closeText: 'Κλείσιμο',
    prevText: 'Προηγούμενο',
    nextText: 'Επόμενο',
    monthNames: ['Ιανουάριος','Φεβρουάριος','Μάρτιος','Απρίλιος','Μάϊος','Ιούνιος','Ιούλιος','Άυγουστος','Σεπτέμβιος','Οκτώβριος','Νοέμβριος','Δεκέμβριος'],
    monthNamesShort: ['Ιαν','Φεβ','Μαρ','Απρ','Μαι','Ιουν', 'Ιουλ','Αυγ','Σεπ','Οκτ','Νοε','Δεκ'],
    dayNames: ['Κυριακή','Δευτέρα','Τρίτη','Τετάρτη','Πέμπτη','Παρασκευή','Σάββατο'],
    dayNamesShort: ['Κυρ','Δευ','Τρι','Τετ','Πεμ','Παρ','Σαβ'],
    dayNamesMin: ['Κ','Δ','Τρ','Τε','Πε','Πα','Σ'],
    weekHeader: 'Εβδ',
    firstDay: 1,
    isRTL: false,
    showMonthAfterYear: false,
    yearSuffix: '',
    timeOnlyTitle: 'Επιλογή Ώρας',
    timeText: 'Χρόνος',
    hourText: 'Ώρα',
    minuteText: 'Λεπτό',
    secondText: 'Δεύτερολεπτο',
    currentText: 'Τώρα',
    ampm: false,
    month: 'Μήνας',
    week: 'Εβδομάδα',
    day: 'Μέρα',
    allDayText : 'Όλη Μέρα'
};