PrimeFaces.locales ['sv_SE'] = {
    closeText: 'Stäng',
    prevText: 'Föregående',
    nextText: 'Nästa',{code}
    monthNames: ['januari', 'februari', 'mars', 'april', 'maj', 'juni', 'juli', 'augusti', 'september', 'oktober', 'november', 'december' ],
    monthNamesShort: ['jan', 'feb', 'mar', 'apr', 'maj', 'jun', 'jul', 'aug', 'sep', 'okt', 'nov', 'dec' ],
    dayNames: ['söndag', 'måndag', 'tisdag', 'onsdag', 'torsdag', 'fredag', 'lördag'],
    dayNamesShort: ['sön', 'mån', 'tis', 'ons', 'tor', 'fre', 'lör'],
    dayNamesMin: ['sö', 'må', 'ti', 'on', 'to', 'fr', 'lö'],
    weekHeader: 'Vecka',
    firstDay: 1,
    isRTL: false,
    showMonthAfterYear: false,
    yearSuffix:'',
    timeOnlyTitle: 'Endast tid',
    timeText: 'Tid',
    hourText: 'timmar',
    minuteText: 'minuter',
    secondText: 'sekunder',
    currentText: 'Nuvarande datum',
    ampm: false,
    month: 'månad',
    week: 'vecka',
    day: 'dag',
    allDayText: 'Hela dagen'
};